# Generated by Django 5.1.2 on 2024-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_alter_billingdetail_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rambutanpost',
            old_name='price_per_kg',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='rambutanpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rambutanpost',
            name='variety',
        ),
        migrations.AddField(
            model_name='rambutanpost',
            name='product',
            field=models.CharField(choices=[('binjai', 'Binjai'), ('caesar', 'Caesar'), ('e35', 'E35'), ('hg_deli_baling', 'Hg Deli Baling'), ('jarum_emas', 'Jarum Emas'), ('mahalika', 'Maharlika'), ('malwana', 'Malwana'), ('muar_gading', 'Muar Gading'), ('rambutan_n18', 'Rambutan N18'), ('rongrien', 'Rongrien'), ('school_boy', 'School Boy'), ('other', 'other')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rambutanpost',
            name='quantity_type',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('litre', 'Litres')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rambutanpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rambutanpost',
            name='image',
            field=models.ImageField(upload_to='rambutan_images/'),
        ),
        migrations.AlterField(
            model_name='rambutanpost',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
