# Generated by Django 5.1.2 on 2024-10-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_rename_price_per_kg_rambutanpost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rambutanpost',
            name='product',
            field=models.CharField(choices=[('Muar Gading', 'Muar Gading'), ('Caesar', 'Caesar'), ('Hg Deli Baling', 'Hg Deli Baling'), ('Jarum Emas', 'Jarum Emas'), ('E35', 'E35'), ('Binjai', 'Binjai'), ('Malwana', 'Malwana'), ('School Boy', 'School Boy'), ('Maharlika', 'Maharlika'), ('Rongrien', 'Rongrien'), ('Rambutan N18', 'Rambutan N18'), ('other', 'Other')], max_length=255),
        ),
    ]
