# Generated by Django 5.1.2 on 2024-10-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_alter_rambutanpost_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rambutanpost',
            name='category',
            field=models.CharField(choices=[('fresh_fruit', 'Fresh Fruit'), ('juice', 'Juice'), ('pickle', 'Pickle'), ('wine', 'Wine')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rambutanpost',
            name='product',
            field=models.CharField(choices=[('other', 'Other'), ('Binjai', 'Binjai'), ('Caesar', 'Caesar'), ('E35', 'E35'), ('Hg Deli Baling', 'Hg Deli Baling'), ('Jarum Emas', 'Jarum Emas'), ('Maharlika', 'Maharlika'), ('Malwana', 'Malwana'), ('Muar Gading', 'Muar Gading'), ('Rambutan N18', 'Rambutan N18'), ('Rongrien', 'Rongrien'), ('School Boy', 'School Boy')], max_length=255),
        ),
    ]
